# Generated by Django 5.0.2 on 2024-05-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pricepernight', models.IntegerField(null=True)),
                ('numberofmasterbedrooms', models.IntegerField(null=True)),
                ('numberofbedrooms', models.IntegerField(null=True)),
                ('numberofbathrooms', models.IntegerField(null=True)),
                ('numberoflivingarea', models.IntegerField(null=True)),
                ('kitchen', models.BooleanField(default=True)),
                ('pictures', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
