# Generated by Django 5.0.2 on 2024-05-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suite',
            name='numberofbathrooms',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='suite',
            name='numberofbedrooms',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='suite',
            name='numberoflivingarea',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='suite',
            name='numberofmasterbedrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='suite',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='suite',
            name='pricepernight',
            field=models.IntegerField(default=200),
        ),
    ]
