# Generated by Django 5.0.2 on 2024-05-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_suite_numberofbathrooms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pricepernight', models.IntegerField(default=200)),
                ('numberofbedrooms', models.IntegerField(default=1)),
                ('typeofbed', models.CharField(default='Double bed', max_length=100)),
                ('numberofbathrooms', models.IntegerField(default=1)),
                ('pictures', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='VIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pricepernight', models.IntegerField(default=500)),
                ('numberofmasterbedrooms', models.IntegerField(default=1)),
                ('typeofbedinmastersbedroom', models.CharField(default='Queen size bed', max_length=100)),
                ('numberofbedrooms', models.IntegerField(default=2)),
                ('typeofbedinotherrooms', models.CharField(default='Double bed', max_length=100)),
                ('numberofbathrooms', models.IntegerField(default=3)),
                ('numberoflivingarea', models.IntegerField(default=1)),
                ('kitchen', models.BooleanField(default=True)),
                ('pictures', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='suite',
            name='typeofbedinmastersbedroom',
            field=models.CharField(default='King size bed', max_length=100),
        ),
        migrations.AddField(
            model_name='suite',
            name='typeofbedinotherrooms',
            field=models.CharField(default='Double bed', max_length=100),
        ),
        migrations.AlterField(
            model_name='suite',
            name='numberofbedrooms',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='suite',
            name='pricepernight',
            field=models.IntegerField(default=1500),
        ),
    ]
