# Generated by Django 5.0.2 on 2024-05-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_standard_vip_suite_typeofbedinmastersbedroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suite',
            name='name',
            field=models.CharField(default='Suite {id}', max_length=100),
        ),
    ]
