# Generated by Django 5.0.2 on 2024-05-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_suite_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='pricepernight',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='suite',
            name='pricepernight',
            field=models.IntegerField(default=2500),
        ),
        migrations.AlterField(
            model_name='vip',
            name='pricepernight',
            field=models.IntegerField(default=100),
        ),
    ]
