# Generated by Django 5.0.2 on 2024-05-12 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_suite_numofsuites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suite',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.suite')),
            ],
        ),
    ]
