# Generated by Django 5.0.2 on 2024-05-12 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_alter_suite_name_room'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='SuiteRooms',
        ),
    ]
