# Generated by Django 5.0.2 on 2024-05-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_rename_room_suiterooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='pricepernight',
            field=models.IntegerField(default=1000),
        ),
        migrations.DeleteModel(
            name='SuiteRooms',
        ),
    ]
