# Generated by Django 5.0.2 on 2024-06-03 00:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_alter_vip_pricepernight_delete_suiterooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('room_type', models.CharField(choices=[('suite', 'suite'), ('vip', 'VIP'), ('standard', 'Standard')], max_length=10)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('number_of_rooms', models.IntegerField(default=1)),
                ('booking_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
