# Generated by Django 5.0.2 on 2024-06-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0014_remove_book_room_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='check_in',
            field=models.DateField(help_text='yyyy-mm-dd'),
        ),
        migrations.AlterField(
            model_name='book',
            name='check_out',
            field=models.DateField(help_text='yyyy-mm-dd'),
        ),
    ]
