# Generated by Django 5.0.2 on 2024-07-13 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0015_alter_book_check_in_alter_book_check_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='book',
            name='check_out',
        ),
    ]
