# Generated by Django 5.0.2 on 2024-07-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0016_remove_book_check_in_remove_book_check_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='check_in',
            field=models.DateField(default='2024-10-11', help_text='yyyy-mm-dd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='check_out',
            field=models.DateField(default='2024-10-12', help_text='yyyy-mm-dd'),
            preserve_default=False,
        ),
    ]
