# Generated by Django 5.0.2 on 2024-07-17 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0018_alter_vip_numberofbedrooms_alter_vip_pricepernight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suite',
            name='numofSuites',
        ),
    ]
