# Generated by Django 5.0.2 on 2024-07-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0019_remove_suite_numofsuites'),
    ]

    operations = [
        migrations.AddField(
            model_name='suite',
            name='numofSuites',
            field=models.IntegerField(default=0),
        ),
    ]
