# Generated by Django 5.0.2 on 2024-05-22 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('rooms', '0011_alter_vip_pricepernight_delete_suiterooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_rooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='standard',
            name='standard',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rooms.standard'),
        ),
        migrations.AddField(
            model_name='suite',
            name='suite',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rooms.suite'),
        ),
        migrations.AddField(
            model_name='vip',
            name='vip',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rooms.vip'),
        ),
    ]
